#######################################
## MAKEFILE for Dataset Construction ##
#######################################

TEST-SITE:= citynetwork.se
TEST-FOLDER:=$(TEST-SITE)-scan/

test:
	rm -rf $(TEST-FOLDER)
	python query-nameserver.py 

